version: '3'
services:
  mongo:
    build: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGO_INITDB_DATABASE: testdb
  node:
    # restart: always
    image: "node:8"
    user: "node"
    working_dir: /home/node/app/api
    environment:
      - NODE_ENV=dev
    volumes:
      - ../:/home/node/app
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - SECRET=lol
      - MONGO_URL=mongodb://usr:pwd@mongo:27017/testdb
    command: "npm start"
